from collections import deque
from typing import List, Tuple

class DSU:
    """Disjoint-set union with path compression + union by size."""
    def __init__(self, n: int):
        self.parent = list(range(n))
        self.size = [1] * n

    def find(self, a: int) -> int:
        while self.parent[a] != a:
            self.parent[a] = self.parent[self.parent[a]]
            a = self.parent[a]
        return a

    def union(self, a: int, b: int) -> None:
        ra, rb = self.find(a), self.find(b)
        if ra == rb:
            return
        if self.size[ra] < self.size[rb]:
            ra, rb = rb, ra
        self.parent[rb] = ra
        self.size[ra] += self.size[rb]

def is_equivalently_css(symp: List[List[int]]) -> bool:
    """
    Decide whether a stabilizer GENERATOR SET is *equivalently CSS* (aka 'nearly CSS'):
    there exists a local Clifford (generated by H and S; equivalently any 1-qubit Clifford)
    that maps every generator (row) to either pure X-type or pure Z-type.

    Input:
        symp: m x (2n) binary matrix in [Z | X] convention.

    Output:
        True  if equivalently CSS for the given generator set
        False otherwise

    Important:
        This checks the condition for the given rows as-is.
        If you also allow changing the generating set by multiplying stabilizers
        (row operations over F2), that's a different decision problem.
    """
    m = len(symp)
    two_n = len(symp[0])
    if any(len(row) != two_n for row in symp):
        raise ValueError("All rows must have the same length.")
    if two_n % 2 != 0:
        raise ValueError("Matrix must have 2n columns.")
    n = two_n // 2

    # DSU components enforce equality constraints between generator indices (rows)
    dsu = DSU(m)
    # Inequality constraints recorded between representatives (later mapped to DSU roots)
    diff_edges: List[Tuple[int, int]] = []

    for q in range(n):
        X_rows, Y_rows, Z_rows = [], [], []
        zcol, xcol = q, n + q

        # Classify which generators have X/Y/Z on qubit q
        for r in range(m):
            z = symp[r][zcol] & 1
            x = symp[r][xcol] & 1
            if z == 0 and x == 0:
                continue
            if z == 1 and x == 0:
                Z_rows.append(r)
            elif z == 0 and x == 1:
                X_rows.append(r)
            else:  # z==1 and x==1
                Y_rows.append(r)

        # Local-2-letter condition: at most two of {X,Y,Z} can appear at one qubit
        nonempty = [lst for lst in (X_rows, Y_rows, Z_rows) if lst]
        if len(nonempty) > 2:
            return False

        # Equality constraints within each nonempty letter class
        for cls in (X_rows, Y_rows, Z_rows):
            if len(cls) >= 2:
                rep = cls[0]
                for rr in cls[1:]:
                    dsu.union(rep, rr)

        # If exactly two letters appear, their corresponding generator-classes must be opposite types
        if len(nonempty) == 2:
            diff_edges.append((nonempty[0][0], nonempty[1][0]))

    # Build quotient graph on DSU roots using inequality edges
    adj = {}
    for a, b in diff_edges:
        ra, rb = dsu.find(a), dsu.find(b)
        if ra == rb:
            return False  # contradiction: same component forced to be different
        adj.setdefault(ra, []).append(rb)
        adj.setdefault(rb, []).append(ra)

    # Bipartiteness check
    color = {}
    for start in adj:
        if start in color:
            continue
        color[start] = 0
        dq = deque([start])
        while dq:
            u = dq.popleft()
            for v in adj.get(u, []):
                if v not in color:
                    color[v] = 1 - color[u]
                    dq.append(v)
                elif color[v] == color[u]:
                    return False

    return True

def is_code_css(code):
    return is_equivalently_css(code.get_stabilizers())
