#!/bin/bash
#SBATCH -n 1  # number of cores
#SBATCH -t 0-12:00  # Runtime DAYS-HRS:MIN
#SBATCH -p mit_normal  # Node partition, don't change this
#SBATCH --mem-per-cpu=4GB  # Request memory per CPU
#SBATCH -o out/out_%A_%a.txt  # Redirect output to output_JOBID.txt
#SBATCH -e err/err_%A_%a.txt  # Redirect errors to error_JOBID.txt
#SBATCH --mail-type=END  # Mail when job ends
#SBATCH --mail-user=khesin@mit.edu  # Email recipient

eval "$("$HOME/.local/bin/micromamba" shell hook -s bash)"
micromamba activate gap
python filter.py -i NAdata33 -z 3 -x 3 -k 2 -g -s 3 -t 3600 -n $SLURM_ARRAY_TASK_ID
